### ISSUE TITLE
Oops, something went wrong.

### ISSUE THREAD

**Issue by CaddyDz** [wakatime/wakatime#113]
Wakatime is active on my editor(s) plugins but I can't access the dashboard on wakatime.com/dashboard  
This is the error message I'm getting (not very helpful), btw this is tested on different computers and browsers with cached cleared  
![screenshot from 2017-11-30 11-19-05](https://user-images.githubusercontent.com/13698160/33425861-4e5896d4-d5c0-11e7-868a-9e34f96ec6fd.png)

**Comment by alanhamlett** [comment]
The request is timing out, so it displays a generic error message. This is a caching issue on our end. We're actively working this month to migrate a large part of our infrastructure to a new architecture because of caching bottlenecks that cause the dashboard error that you're experiencing.

For now, just try refreshing the page. Things will get better with the website performance soon!

**Comment by CaddyDz** [comment]
It's working now, thanks a lot

**Comment by alanhamlett** [comment]
Let's leave this open while things are being improved, since it might timeout periodically still.

**Comment by dezio** [comment]
Yes, I'm facing the same problem since subscribed to a paid plan.

**Comment by dezio** [comment]
I don't know if this is normal, I would have expect to get something other than

> Oh Snap! WakaTime needs JavaScript for all the pretty graphs and charts.
> Please enable JavaScript in your browser to view the site.

**Comment by alanhamlett** [comment]
@dezio That means you disabled JavaScript in your browser.

**Comment by alanhamlett** [comment]
Current timeline for a permanent fix is end of December / early January.

**Comment by alanhamlett** [comment]
There's an unrelated issue with versions 10.0.1 through 10.0.4 of [wakatime-cli](https://github.com/wakatime/wakatime/blob/master/HISTORY.rst) that keeps your coding activity locally without sending it to your dashboard. It's not related to the dashboard error message, but and can be easily fixed by updating WakaTime plugins and restarting your IDE. Even if your WakaTime plugin says it's the latest version, make sure your WakaTime CLI version is up to date by restarting your editor/IDE. Use this plugin status page to check your editors:

https://wakatime.com/plugin-status

**Comment by sanijajoy** [comment]
wakatime/wakatime I believe every single individual perspectives will see the truth," Via comment 
My name is human and I believe............

**Comment by VicoErv** [comment]
Using charles as mitm make same problem, and it disappear when i turn off mitm proxy. maybe certificate issue?

**Comment by KrunchMuffin** [comment]
Something is most definitely awry. This should be all up in the 8-10hr range almost every day.

![image](https://user-images.githubusercontent.com/1037197/34144725-d82d0e72-e460-11e7-8f90-31ef003e3ea3.png)

**Comment by alanhamlett** [comment]
Closing this as fixed. Re-allowing comments here. If you're still having a slow dashboard, please let me know!

**Comment by YassineGherbi** [comment]
I'm still having this error message on the dashboard when selecting a range larger than 1 month. Any workaround?

**Comment by alanhamlett** [comment]
@YassineGherbi for ranges over 1 month, just refresh and the dashboard should load the second time.
