### ISSUE TITLE
Email Notifications from Wakatime Site Goals

### ISSUE THREAD

**Issue by int0x01** [wakatime/wakatime#122]
Apologies if this is an inappropriate place to create this issue (since it doesn't have anything to do with the CLI, but the site).

I'm a free user and I currently have a Wakatime goal: "I want to code at least 8 hours per day, except for Saturday, Sunday."

In the previous goal system, I would receive an email once every week summarizing whether or not I met the goal for that week. Starting February 1st through today, I've received the weekly email every day. I was wondering if this was a bug, or if there was a way of disabling these daily email notifications.

Thanks!

**Comment by alanhamlett** [comment]
To change your notification frequency, go to https://wakatime.com/goals and click the settings icon at the top right of your goal. There's also a direct link at the bottom of your goal email titled `Change the frequency of these emails`.

![goal-subscribe](https://user-images.githubusercontent.com/522344/35843844-3f8bcc8c-0abf-11e8-97e2-3829c0223ca8.gif)

**Comment by int0x01** [comment]
Bah completely missed that, thanks. I think it might be more discoverable if there was no "Subscribed" section and all the information was available in "Edit", but of course I do not know what is going on in the UI of the paid product or in teams.

**Comment by aymannageeb** [comment]
Hallo,
There's one way to stop the incoming posts with asking for a monthly
waktime not daily.
Perhaps it will work with you.
And about the 8 uhr programming how it’s going on? Momenten I do work to
Programm three Programms in one ( windows-linoxs-And I try to add Mac )
under one program but I got problems because right now it works good with
me but my pc don’t accept cmd orders? Do you have any idea! With know that
everything works good and there's no viros ,
I do work every day Two Uhrs pragraming !
I will wait your up coming emails and I would like to run between us Skype
Kontakt in this weekend ?
Thanks for your time .
Best wishes .

**Comment by alanhamlett** [comment]
@aymannageeb please email support@ for help with specific account debugging.
