### ISSUE TITLE
Feature Request: Add support for VueJS

### ISSUE THREAD

**Issue by n1try** [wakatime/wakatime#180]
Recognize `*.vue` files as VueJS "language" or, alternatively, JavaScript.

**Comment by alanhamlett** [comment]
That's already supported since we have a server side rule for `*.vue` extensions:

<img width="728" alt="Screen Shot 2019-05-21 at 7 10 16 AM" src="https://user-images.githubusercontent.com/522344/58103273-91542600-7b97-11e9-8173-c70faf2cec86.png">

That rule forces files ending with `*.vue` to be detected as `Vue.js` language.
