### ISSUE TITLE
Heartbeats not sent from Vim on VPS accessed via SSH

### ISSUE THREAD

**Issue by michaelgill1969** [wakatime/wakatime#189]
My dashboard is not logging time spent in Vim on a CentOS 7 VPS accessed via SSH.  I can enable and disable debugging, at least so far as debug is toggled in .wakatime.cfg.  However, there is no .wakatime.log in my home directory after editing a file in Vim.  I installed using Pathogen.

Issue #72 indicates that this should work over SSH, right?

**Comment by alanhamlett** [comment]
Yes, using Vim via ssh is same as using it from a local shell so the plugin should work. Is Python installed on the VPS? Does the vim command `:WakaTimeToday` show your coding stats printed?

**Comment by michaelgill1969** [comment]
Python 2 is installed and `:WakaTimeToday` shows "Today: 1 min".

I do have .wakatime.log now, although it is empty.  The .wakatime.db is not empty.

What about firewalld?  Do I need to open a port or something?

**Comment by alanhamlett** [comment]
> What about firewalld? Do I need to open a port or something?

Probably not, since the today command printed your stats that means it was able to connect to our API from your Vim inside the VPS.

> The .wakatime.db is not empty.

That's an sqlite file with offline heartbeats and other things cached, so it has non-zero file size but might still be empty if the `heartbeat_2` table has no rows. With debug mode enabled, heartbeats going to that `.wakatime.db` write a log to `.wakatime.log` so with an empty log file the `.wakatime.db` file is probably also empty. Unless you only had debug mode enabled for a short time without generating any coding activity.

> I do have .wakatime.log now, although it is empty.

With debug mode enabled, Vim should echo any error message at the bottom of screen. Otherwise, there's always at least some logging happening in `.wakatime.log`. Since you have neither I'm not sure what's happening.

You could try adding this code to line 361 of your installed plugin's `wakatime.vim` file:
`echo '[WakaTime] Heartbeat Command: ' . s:JoinArgs(cmd)`
Then restart Vim, type in a file, copy the printed command into a shell and run it outside of Vim to see if any errors are printed that Vim is suppressing.

**Comment by michaelgill1969** [comment]
It's now logging normally with the following:
```
{"now": "2019/08/08 02:14:24 +0000", "version": "12.0.0", "plugin": "vim/704 vim-wakatime/8.0.0", "time": 1565244843.001377, "caller": "/home/michael/.vim/bundle/vim-wakatime/packages/wakatime/main.py", "lineno": 58, "file": "/home/michael/temp", "level": "DEBUG", "message": "File does not exist; ignoring this heartbeat."}
```

**Comment by alanhamlett** [comment]
That means the file being edited in Vim couldn't be found by the WakaTime plugin, so it's not logging that activity. When you go to the plugin status page do you see Vim listed as working and recently heard from?
https://wakatime.com/plugins/status

**Comment by michaelgill1969** [comment]
It only lists the activity from Vim on my local computer, which was last seen 30 days ago.

**Comment by michaelgill1969** [comment]
It's working now.  First on my local Vim installation on macOS 10.14.6 (which needed updating but probably had nothing to do with this issue), and then on my remote installation on CentOS 7.6.1810, I did the following:

1. Move all WakaTime files in home directory (~): e.g.: `mv .wakatime.cfg wakatime.cfg`;
2. Remove all hidden WakaTime files in home directory: `rm . wak*`;
3. Remove WakaTime files installed via Pathogen from ~/.vim/bundle: `rm -rf vim*`;
4. Reinstall WakaTime via Pathogen.

It also seems to have logged all or most of my time in Vim over the past couple of days when I've been working in my VPS.

As usual, thanks for your help, @alanhamlett.  I always seem to be able to trust that you'll be around when I need you!  :)
