### ISSUE TITLE
Commit tracking

### ISSUE THREAD

**Issue by paulandrieux** [wakatime/wakatime#5]
It would be great that Wakatime could track commits. I'd love to see how much time I spend on each task on my projects. What do you think ?

**Comment by alanhamlett** [comment]
This is now available on the site by clicking the "commits" link on a project's page.

**Comment by devinaconley** [comment]
Sorry to comment on an old issue - was support for tracking commits via local logs ever added? Thanks

**Comment by J3m5** [comment]
It seems that the tracking time assigned to each commits doesn't reflect the sum of the coding times of each files added to the commit but rather the total of the coding time of the project since the last commit.

It is correct only if you code only on the files you commit between each commits and if your commit contain all the files that you have worked on.

The logic should be: 
Get the sum of the coding time of the files added to the commit since the last time they was committed.

**Comment by alanhamlett** [comment]
@J3m5 you're correct, that's been a limitation of commit times. We need to only add time from files contained in a commit, and also support branches other than master.

**Comment by J3m5** [comment]
@alanhamlett It would be great if it were implemented, it would allow us to track the time we spend on specific features and then use it to invoice out clients with the help of the API.
Even if it's limited to the master branch, it would be a good start.

**Comment by J3m5** [comment]
Hi @alanhamlett, I've stopped my subscription because of this missing functionality. 
We really need to track the time spend on commits related to certain issues based on customer quotes.
Could you allocate some time for it please?
Thank you

**Comment by alanhamlett** [comment]
We're working on improving this. To start, we've added support for multiple branches other than master.

**Comment by nelson6e65** [comment]
Hi. I would like to, also, be compatible with partial commits.

For example, I work 3 hours but I make multiple commits when I finish a stable update. I make 3 commits and I get: 

- Typo in `README.md`  **(3h)**
- Improve UI: `page1.html` + `pages.scss` files **(0s)**
- Improve speed of `api.js` **(0s)**

Instead of expected:

- Typo in `README.md`  **(10s)**
- Improve UI: `page1.html` + `pages.scss` files **(2h)**
- Improve speed of `api.js` **(1h)**

**Comment by J3m5** [comment]
@nelson6e65 This ties in with what I was saying [there](https://github.com/wakatime/wakatime/issues/5#issuecomment-517275067), the time is calculated by adding the sum of the last coding time without taking into account each individual files of each commits.
It would only works if we would code only in the files contained in each commits and push each commits after it's finished, sequentially.
It's a first, simple and naive approach that I hope will be improved soon.

**Comment by J3m5** [comment]
Any news @alanhamlett ?

**Comment by alanhamlett** [comment]
We've refactored commits and how they're associated with authors' corresponding WakaTime accounts, which was the first step. Next we're adding a filter, to match files from commits with corresponding WakaTime project files. The new formula will be the default, and we might have the ability to toggle between the old and new ways.

Regarding ETA, I don't have a release time yet since we're focused fully on wakatime-cli rewrite into Go for all the plugins.

**Comment by J3m5** [comment]
> Another question is what to do with time from files not in a commit. How long does that time wait to be associated to a commit?

Isn't that time already stored indefinitely ?
Currently, we can know how much time we code in any file at any date, no ?

I don't know how it works internally, but I guess you would compute the time of the commit by retrieving the date of the last time the file was committed if it was and query the time based on that date until the current commit.

**Comment by alanhamlett** [comment]
> retrieving the date of the last time the file was committed if it was and query the time based on that date until the current commit

Yep, but that's an expensive query to be running for such a long time range. To have to run that query on every file in a commit could take a long time. That's why we have to decide a maximum time range for the query, for ex: if you edit a file but don't commit the change until a year later then the commit shows no time for that file.

**Comment by J3m5** [comment]
Ok, I see.

Another solution could be to store a row per file per branch and per commit ( when it has been commited).

I don't know if it's already the case, but it didn't look like it the last time I checked the API.

It would increase the database size and the amount of updates but the queries
 would be much less costly as the time would be already computed and the computation can be done only each time it is requested and not continuously (lowering the amout of updates).

I don't know what database you are using but I  materialized views would be good fit for this kind of feature.

**Comment by alanhamlett** [comment]
We mainly use Postgres, S3, SSDB, and Redis. Time per commit is long term cache data, so it goes into SSDB.

**Comment by alanhamlett** [comment]
Thinking through matching time spent per file to the diff of commits, it still breaks down when two commits change the same file. I think the only way to get accurate time spent per commit is use one branch per feature. Then always commit and switch branch instead of stash.
