### ISSUE TITLE
Commit Times from GitLab

### ISSUE THREAD

**Issue by Nalum** [wakatime/wakatime#71]
Not sure this is the right repo for this issue.

Times for commits in repos on gitlab.com are not shown.

![wakatime](https://cloud.githubusercontent.com/assets/384180/21677495/5be734a4-d332-11e6-8421-893989dffd51.png)

**Comment by light2yellow** [comment]
This is definitely not related to Wakatime. You need to hover the date with your mouse to get more details.
<img width="418" alt="screen shot 2017-02-02 at 10 00 15" src="https://cloud.githubusercontent.com/assets/10786469/22542911/72528182-e92e-11e6-9a00-e2e72108f4d2.png">

**Comment by Nalum** [comment]
@light2yellow sorry wasn't clear enough in the original issue. What I mean is that the time worked on per commit is not being shown the same way it is shown for github.

From what I understand there is supposed to be a duration on the far right side of the image above.

**Comment by light2yellow** [comment]
@Nalum didn't even know about this feature. I cannot help you with this, sorry.

**Comment by alanhamlett** [comment]
@Nalum have you connected a WakaTime project to a GitHub project? Make sure the project has a GitHub icon next to it when listed here:
https://wakatime.com/integrations/github

After that's finished, it should display the coding activity for your GitHub username next to each of your commits.

**Comment by Nalum** [comment]
@alanhamlett the issue I'm having is with GitLab but yes I have connected to both GitHub and GitLab.

**Comment by alanhamlett** [comment]
Just fixed this by looking up your GitLab username when unable to match a GitLab committer's email to a WakaTime account.

GitLab doesn't show usernames for commits in their API, so we had to match the committer's email against your WakaTime email. Since your emails are different on GitLab and WakaTime, we weren't able to match your coding activity to your commits. It's fixed now by keeping a cache of emails to usernames.
