### ISSUE TITLE
Support remote files over network drive, ftp, or ssh

### ISSUE THREAD

**Issue by MartinNowack** [wakatime/wakatime#72]
Files are not tracked if they are not accessible via local filesystem:
https://github.com/wakatime/wakatime/blob/eef70499e712d3dd34f93c872018642912db3b6b/wakatime/heartbeat.py#L235

This is a pity for working with remote systems and non-local files.
I guess this influences almost all editor plugins, which support working with remote file systems.

I worked around it by disabling the check for file existence.

**Comment by alanhamlett** [comment]
It would be good to support remote file systems. To do that, a few requirements must be met:

* Temporary/swap/meta files must not be tracked (the original reason for requiring the file exist)
* Each editor plugin must pass the correct remote file path to wakatime-cli. Currently some mangle remote file paths by prepending with a slash.
* wakatime-cli should recognize remote vs local file paths and prevent checking if the file exists for remote paths, because that could cause lag or other performance issues.

**Comment by alanhamlett** [comment]
WakaTime will either lazy-download or bundle [pywin32](https://github.com/mhammond/pywin32) then use `win32wnet.WNetGetUniversalName(args.entity, 1)` to fix this in the future.

**Comment by alanhamlett** [comment]
On second thought, pywin32 is overkill when we could just parse output from `net use` command:

```
>net use
New connections will be remembered.


Status       Local     Remote                    Network

-------------------------------------------------------------------------------
             E:        \\vboxsrv\Desktop         VirtualBox Shared Folders
```

**Comment by alanhamlett** [comment]
6b678942f072b4abfcb77bc812a5818b5c2867ea adds support for network drives.

**Comment by alanhamlett** [comment]
Closing this with release of 10.4.0. We can open a new separate issue for ftp/ssh files if needed.
