### ISSUE TITLE
Ability to Pause/Resume tracking

### ISSUE THREAD

**Issue by Abhinickz** [wakatime/wakatime#94]
Feature Request:
Need Start/Pause Buttons in Wakatime Plugin on Notepad++

Because most of the time I keep open Notepad++ not just for coding but for also looking up the important text files saved So in meantime I code on Vim Editor Or I am doing something else and Notepad++ is just open without doing any coding.

With the given Start/Pause button I can control time login.

**Comment by alanhamlett** [comment]
The plugins only track coding activity when you're using the editor. If Notepad++ is open but you're using Vim, does the Notepad++ plugin still think you're actively coding? If so, can you file that as a bug here: https://github.com/wakatime/notepadpp-wakatime/issues/new

**Comment by Abhinickz** [comment]
No, Actually If I am not coding and Notepad++ is still open just with simple text file, wakatime also thinks that I am coding actively.

That's why there should be some ability to Pause/Resume tracking.

**Comment by alanhamlett** [comment]
Nope, WakaTime only tracks coding activity when you're using Notepad++ and automatically stops tracking when you are not typing or scrolling in the text file.

Since WakaTime is fully automatic, we won't add a pause/resume button.

Related to this is [excluding folders completely from WakaTime using regex patterns](https://wakatime.com/faq#exclude-paths).
